# Generated by Django 4.0.4 on 2022-04-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
