# Generated by Django 4.0.4 on 2022-04-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_person_2_alter_room_person_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
