# Generated by Django 4.0.4 on 2022-04-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('rooms', '0007_alter_room_person_1_alter_room_person_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='person_1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='person_1', to='registration.appuser'),
        ),
        migrations.AlterField(
            model_name='room',
            name='person_2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_2', to='registration.appuser'),
        ),
        migrations.AlterField(
            model_name='room',
            name='person_3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_3', to='registration.appuser'),
        ),
        migrations.AlterField(
            model_name='room',
            name='person_4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_4', to='registration.appuser'),
        ),
    ]
