# Generated by Django 4.0.4 on 2022-04-22 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('rooms', '0008_alter_room_person_1_alter_room_person_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(max_length=1)),
                ('num', models.PositiveIntegerField()),
                ('point', models.PositiveIntegerField()),
                ('img', models.ImageField(upload_to='cards/')),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_user_of_card', to='registration.appuser')),
            ],
        ),
    ]
