# Generated by Django 4.0.4 on 2022-04-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
