# Generated by Django 4.0.4 on 2022-04-22 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('rooms', '0010_deck_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='app_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='app_user_of_card', to='registration.appuser'),
        ),
    ]
