# Generated by Django 4.0.4 on 2022-04-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_alter_deck_app_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deck',
        ),
    ]
