# Generated by Django 4.0.4 on 2022-04-22 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('rooms', '0012_delete_deck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(max_length=1)),
                ('card_no', models.CharField(max_length=2)),
                ('priority', models.PositiveIntegerField()),
                ('point', models.PositiveIntegerField()),
                ('img', models.ImageField(upload_to='cards/')),
                ('is_trump', models.BooleanField(default=False)),
                ('app_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='app_user_of_card', to='registration.appuser')),
            ],
        ),
    ]
