# Generated by Django 4.0.4 on 2022-04-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_remove_deck_app_user_remove_deck_is_trump_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
