# Generated by Django 4.0.4 on 2022-04-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card', to='rooms.deck'),
        ),
    ]
